### ISSUE TITLE
**plan_cuentas_mongo** Proceso Parametrizar estado de los CDP y CRP , y compromisos , y pruebas -Afectacion de los movimientos

### ISSUE THREAD

**Issue by miguelramirez93** [udistrital/plan_cuentas_mongo_crud#100]
- [x]  Revisar funcionamiento de propagación de saldos
- [x] parametrizar los nuevos movimeintos
- [x] ajustar algoritmos de propagación
- [x] ajustar algoritmo para realizar cambios de estado

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/plan_cuentas_mid/commit/0de2eadb67744e57c15b7d0f15d1a3efa001f5d3 se ajustan modelos de mid para empalmar cambios

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/movimientos_crud/commit/2aa1bde6e7264729148586a8b20f65b8288d9f22 se añaden nuevos tipos de movimientos para cdp y rp

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/plan_cuentas_mid/commit/486d00c356306c9d287b79390c5b11cd18a82f6c se añaden objetos y modifican funciones para poder registrar un documento presupuestal generalizado

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/plan_cuentas_mid/commit/2187f1e5a3ce3acd1ecc7fef7052409ddb7e9dd9 se ajusta mid para nueva estructura

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/plan_cuentas_mid/pull/27 se realiza pr a mid con los nuevos cambios

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/movimientos_crud/pull/34 se realiza pr con los nuevos tipos de movimiento

**Comment by mcrubianot** [comment]
Se revisa el día de hoy con el ingeniero Francisco en Sicapital y se establece que los estados que actualmente tienen los cdp y los crp son:

CDP
Argumento Resultado
AGOTADO - TOTAL COMPROMETIDO
VIGENTE-AGOTADO PARCIALMENTE COMPROMETIDO
VIGENTE - VIGENTE
ANULADO - ANULADO

CRP
Argumento Resultado
AGOTADO TRAMITADO
VIGENTE-AGOTADO PARCIALMENTE TRAMITADO
VIGENTE - VIGENTE
ANULADO - ANULADO

Considero pertinente el análisis por parte de los desarrollados de cada uno de estos estados para poder establecer las reglas que afectarán cada tipo de documento.

**Comment by mcrubianot** [comment]
Comparto el siguiente documento que establece algunas acciones sobre los tipos de compromiso antes mencionados
https://docs.google.com/document/d/13gvoYbTTu9hzj7dmoj4NV2W-u_-KFPk9QYiXhuNM-jc/edit

**Comment by Soulfilip-UD** [comment]
Tiempo realizando la tarea : 36 horas

Próximas tareas :
- Desplegar plan_cuentas_mid
- Desplegar movimientos_crud

Tarea revisada y finalizada, para revisar los cambios en test se deben realizar las 2 tareas de arriba, buen trabajo.

Proceding to close Issue 👾
