### ISSUE TITLE
Generalizar los estados sobre productos, fuentes y apropiaciones - 16 horas - Miguel

### ISSUE THREAD

**Issue by miguelramirez93** [udistrital/plan_cuentas_mongo_crud#107]
- [x] agregar cambio de estado de documentos en algoritmo de propagación
- [x] genrlaizar algoritmo de propagación de saldos
- [x] generar nuevos párametros para algoritmo de propagación

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/plan_cuentas_mid/commit/4b71e7800ef1585dfa68c2270143c2ad39b2590f se añade vigencia y centro gestor a parametros de documento presupuestales

**Comment by miguelramirez93** [comment]
se realiza pr en https://github.com/udistrital/plan_cuentas_mid/pull/28 para ajustes mid de esta tarea

**Comment by miguelramirez93** [comment]
@Soulfilip-UD Tarea Finalizada , recomiendo primero eliminar la db de mongo y correr el API para hacer migraciones de datos limpias  y empezar a insertar datos ya que tambien se corrigio un problema en la colección de transacciones de mongo

**Comment by Soulfilip-UD** [comment]
Desarrollos revisados y PR aprobados, si entiendo porque debo realizar la limpieza de los datos en esta base de datos, planeamos limpiarla y crear de nuevo los rubros para las pruebas de necesidades y apropiaciones.

Tarea Finalizada
Proceeding to close Issue 👾
