### ISSUE TITLE
**API** Corregir: no se puede editar sobre los rubros o valores de las apropiaciones.  - 3 horas - Miguel

### ISSUE THREAD

**Issue by miguelramirez93** [udistrital/plan_cuentas_mongo_crud#109]
- [x] corregir servicio de registro y actualización de apropiaciones

**Comment by miguelramirez93** [comment]
@Soulfilip-UD Tarea FInalizada

**Comment by Soulfilip-UD** [comment]
Desarrollo revisado y mezclado satisfactoriamente, queda actualizar el API de mi parte en el ambiente de test.

Tarea Finalizada 
Proceeding to close Issue 👾
