### ISSUE TITLE
Ajuste del Mongo API para cargar el arbol de rubros

### ISSUE THREAD

**Issue by miguelramirez93** [udistrital/plan_cuentas_mongo_crud#11]
- [x] Desarrollo de Algoritmo de Contrucción de Arbol de Rubros

- [x] Implementación de Algoritmo de Contrucción en servicio

**Comment by miguelramirez93** [comment]
Se realiza e implementa el algoritmo en (https://github.com/udistrital/plan_cuentas_mongo_crud/pull/13/commits/c36abf27cc735f5e0f58cc559045407860132633)

**Comment by Soulfilip-UD** [comment]
Tarea Realizada!
Proceeding to close Issue :space_invader:
