### ISSUE TITLE
agregar formato al api mongo para los niveles del rubro presupuestal

### ISSUE THREAD

**Issue by davidmm07** [udistrital/plan_cuentas_mongo_crud#111]
- [x] Crear proceso para formatear el codigo del rubro presupuestal.

**Comment by davidmm07** [comment]
PR pendiente para este issue revisión @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
El formato tiene en cuenta los 0 a la izquierda, y el número de dígitos que deben tener como máximo/mínimo por nivel .

Tarea revisada, desplegada y validada en test
Proceeding to close Issue :space_invader:
