### ISSUE TITLE
 Limpiar bd y crear rubros de pruebas necesidades( Fuentes y productos)

### ISSUE THREAD

**Issue by davidmm07** [udistrital/plan_cuentas_mongo_crud#113]
- [x] Limpiar bd y crear rubros de pruebas necesidades( Fuentes y productos)

**Comment by davidmm07** [comment]
Migración exitosa con Los nuevos cambios estructurales en ambiente test( collection arbol_rubro_parameter) a revisión @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Base de datos limpia y Rubros creado , Tarea Finalizada
Proceeding to close Issue 👾
