### ISSUE TITLE
Modificar parametros endpoints

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/plan_cuentas_mongo_crud#139]
Actualize el swagger de plan_cuentas_mongo y hay endpoints que aun tienen el objectid, debe quedar solamente {id} ya que es la principal razón por la que no se puede editar o borrar los registros:

- [x] /necesidades
- [x] /producto
- [x] /solicitudesCDP
- [x] /solicitudesCRP
**revisen todos : GET, POST, PUT**

**Comment by juancsr** [comment]
El **estado de avance de la tarea es de un 20%**, se está priorizando el desarrollo del modulo de necesidades, por eso es que estás tareas de ajustes se están dejando en segundo plano. Se espera finalizarlas después del sprint del 1 de noviembre.

**Comment by Soulfilip-UD** [comment]
Endpoints modificados en el PR #146 
Tarea Finalizada, gracias 👍 

Proceeding to close Issue 👾
