### ISSUE TITLE
Pruebas unitarias: rubros, preasignación, apropiaciones

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/plan_cuentas_mongo_crud#142]
realizar pruebas unitarias para los endpoints de arból de rubros y apropiaciones

**Comment by miguelramirez93** [comment]
Tarea Finalizada @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Ya revise la calidad del código y 👍, para finalizar la tarea debo asegurar que estas lleguen a test, en el momento estoy haciendo una actualización del despliegue que me tomara hasta el viernes en la tarde, por lo tanto reviso y cierro la tarea el viernes 8 Nov en la tarde.

**Comment by Soulfilip-UD** [comment]
API arriba y todo ok 

Proceeding to close Issue 👾
