### ISSUE TITLE
Desarrollo de Traslado en API Mongo, rama contra credito

### ISSUE THREAD

**Issue by juancsr** [udistrital/plan_cuentas_mongo_crud#15]
- [x] Desarrollo de movimiento para traslado de fuente de financiamiento en plan_cuentas_mongo_crud

**Comment by juancsr** [comment]
En espera a las mejoras por parte de @miguelramirez93 en plan_cuentas_mongo_crud para el registro de movimientos, esta tarea se posterga para el martes 9 de julio para reunirse con él y establecer que cambios se realizaron.

**Comment by juancsr** [comment]
En la generalización de Movimientos realizada en el acompañamiento con @miguelramirez93 se manejan los movimientos de traslado.

**Comment by juancsr** [comment]
* **Tipo de petición**: POST
* **Parámetros**:
```json
[
	{ 
		"Valor": 30000000.0,
		"FechaRegistro": "2019-05-01T05:00:00.000Z",
                "DocumentoPadre": 53,
                "IDPsql": 37,
		"Descripcion": "Suspensión a la fuente de financiamiento 3",
		"Tipo": "traslado_contra_credito"
	}
]
```
* **Endpoint**: movimiento/RegistrarMovimientos
* **URL**: http://localhost:8082/v1/movimiento/RegistrarMovimientos

**Comment by Soulfilip-UD** [comment]
Tarea Finalizada, gracias por los comentarios
Proceeding to close Issue 👾
