### ISSUE TITLE
Revisar bugs al registrar/eliminar , validar rubros hasta el 8vo nivel

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/plan_cuentas_mongo_crud#158]
Revisar bugs al registrar/eliminar , validar rubros hasta el 8vo nivel

**Comment by Soulfilip-UD** [comment]
<img width="882" alt="Screen Shot 2019-11-22 at 10 27 26 AM" src="https://user-images.githubusercontent.com/50924615/69438325-d0b02a80-0d12-11ea-819d-e7a3f51af5cc.png">

**Comment by Soulfilip-UD** [comment]
Crear rubros
3-03-001-15-01-43-0388
3-03-001-15-01-08-0389

**Comment by Soulfilip-UD** [comment]
<img width="726" alt="Screen Shot 2019-11-26 at 5 32 01 PM" src="https://user-images.githubusercontent.com/50924615/69738966-e05db380-1104-11ea-9475-3e259013d86a.png">

**Comment by juancsr** [comment]
https://github.com/udistrital/financiera_cliente/issues/609

**Comment by Soulfilip-UD** [comment]
Pruebas realizadas, de acuerdo a la HU en nivel 8vo tiene 4 digitos, el 9no 2 y el 10mo 2
<img width="614" alt="Screen Shot 2019-12-05 at 11 49 40 PM" src="https://user-images.githubusercontent.com/50924615/70296896-ebc27600-17b9-11ea-90a3-9d463f858f38.png">

Tarea finalizada , excelente trabajo
Proceeding to close Issue 👾
