### ISSUE TITLE
Revision y ajustes de modelos de datos para cierre de vigencia y gestion de pasivos y reservas

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/plan_cuentas_mongo_crud#176]
- [x] revisar estado actual de bd a nivel de gestion de vigencias
- [x] revisar estado actual de bd a nivel de gestion de pasivos y reservas
- [x] añadir o modificar los modelos necesarios para gestion de pasivos y reservas
- [x] revision de gestion de movimientos por fecha

**Comment by CarlosGutierrezArdila** [comment]
en conjunto con @NeiderFajardo  se definio que servicios eran necesarios para llamar el cierrede vigencia y articularlo con la tarea #199 se apoyara dicha tarea para que el proceso de gestion de vigencia sea automatizado en el momento del cierre.

**Comment by Soulfilip-UD** [comment]
Se aprueba el modelo de vigencias en el [issue #239](https://github.com/udistrital/presupuesto_cliente/issues/239) 

Asimismo ya se tiene los servicios para cambiar el estado de los CRP a reservas y reservas a pasivos

Tarea finalizada 
Proceeding to close Issue 👾
