### ISSUE TITLE
Incluir fuentes de Financiamiento en API de plan_cuentas_mongo_crud

### ISSUE THREAD

**Issue by davidmm07** [udistrital/plan_cuentas_mongo_crud#18]
- [x] Desarrollar componentes iniciales para fuentes de financiamiento en API de mongo

**Comment by davidmm07** [comment]
Se referencia issue con el PR #21

**Comment by Soulfilip-UD** [comment]
Tarea ompleta y finalizada
Proceeding to close Issue :space_invader:
