### ISSUE TITLE
Crear servicios GET y PUT para documento_presupuestal

### ISSUE THREAD

**Issue by juancsr** [udistrital/plan_cuentas_mongo_crud#187]
- [x] Crear servicio GET

- [x] Crear servicio PUT

- [x] Documentación servicio GET

- [x] Documentación servicio PUT

**Comment by juancsr** [comment]
### Servicio GET
* **Tipo de petición**: GET
* **Parámetros**: se envían por URL
  * :vigencia = vigencia el documento 
  * :areaFuncional = area funcional en la cual fue expedido el documento
  * :id= _id de documento_presupuestal
* **Endpoint**: documento_presupuestal/documento/:vigencia/:areaFuncional/:id

* **URL**: http://localhost:8082/v1/documento_presupuestal/documento/2019/1/ABCDEDF

### Servicio PUT
* **Tipo de petición**: PUT
* **Parámetros**: Es un objecto con la estructura de documento_presupuestal
```json
{    
		"_id": "5deedef3a9e98a04f022d833",
    "Data": {
      "solicitud_cdp": "5de31397d0d9d638497e1c7e"
    },
    "Tipo": "cdp",
    "AfectacionIds": [
      "5deedef3a9e98a04f022d834"
    ],
    "Afectacion": null,
    "FechaRegistro": "2019-12-09T23:55:31Z",
    "Estado": "expedido",
    "ValorActual": 1160000,
    "ValorInicial": 1160000,
    "Vigencia": 2019,
    "CentroGestor": "1",
    "Consecutivo": 4
}
```
* **Endpoint**: documento_presupuestal/:id

* **URL**: http://localhost:8082/v1/documento_presupuestal/ABCDEDF

**Comment by Soulfilip-UD** [comment]
gracias por la documentación, muy buen aporte.

Tarea finalizada
Proceeding to close Issue :space
