### ISSUE TITLE
Desarrollo de Movimiento Presupuestal: Adicion en API mongo

### ISSUE THREAD

**Issue by davidmm07** [udistrital/plan_cuentas_mongo_crud#19]
- [x] Desarrollar función para API mongo

**Comment by davidmm07** [comment]
Tarea a socializar con el equipo de desarrollo el día 09/07/2019, debido al proceso generico de movimientos:
https://github.com/udistrital/plan_cuentas_mongo_crud/commit/757697c2f6687daf1864b24c66fc0f2ef0da81a3
El modelo del documento en mongo sería de 
```sh

{
	"idpsql": int,
	"rubros_afecta": [{
			"Codigo": "string",
			"Valor": float64,
			"Tipo": "string" // Por ejemplo Adición, Reducción
	}],
	"Tipo": "string", // Por ejemplo Apropiaciones, Fuentes, CDP, CRP
	"fecha_registro": "string",
	"unidad_ejecutora": int16
}

```
Una vez hecha la socialización se definira si hay PR para este issue.

**Comment by Soulfilip-UD** [comment]
Excelente la documentación, por favor asociar PR

**Comment by davidmm07** [comment]
El PR asociado #26 aplica el proceso generico de movimientos para el api de mongo

**Comment by Soulfilip-UD** [comment]
Tarea Realizada
Proceeding to close Issue 👾
