### ISSUE TITLE
Agregar fecha final vigencia a CRP

### ISSUE THREAD

**Issue by juancsr** [udistrital/plan_cuentas_mongo_crud#193]
Agregar el atributo fecha final vigencia a CRP para guardar una nueva fecha vinculada al rp.

**Comment by Soulfilip-UD** [comment]
Agregar trazabilidad del desarrollo . PR ?

**Comment by juancsr** [comment]
Merge Asociado

**Comment by Soulfilip-UD** [comment]
Ajustes realizados

Tarea finalziada 
Proceeding to close Issue 👾
