### ISSUE TITLE
Registro de rubros en mongo

### ISSUE THREAD

**Issue by davidmm07** [udistrital/plan_cuentas_mongo_crud#2]
- [x] Revisar problema de la transacción de rubros

**Comment by davidmm07** [comment]
- [ ] Revisar problema de la transacción de rubros

**Comment by juancsr** [comment]
Corregido problema de transacción:

https://github.com/udistrital/plan_cuentas_mongo_crud/commit/220562926996c123f7fbbb2d974ba8cb68f84c22

el problema se daba porque intentaba hacer un type assertion a una interface nil

**Comment by juancsr** [comment]
Para un registro correcto, es necesario enviar el id del registro correspondiente asignado de postgres, antes de enviarlo a mongo. 
Por ejemplo, en este caso, el campo correspondiente se llama Id:
`{
   "RubroPadre":{
      "Id":35922,
      "Codigo":"7"
   },
   "RubroHijo":{
      "Id":34,
      "Vigencia":2019,
      "Entidad":1,
      "Nombre":"test 3 hijo",
      "Codigo":"7-1",
      "Descripcion":"prueba02junio2019",
      "UnidadEjecutora":1,
      "Estado":1,
      "ProductoRubro":null
   }
}`

**Comment by miguelramirez93** [comment]
Se revisa. No se tienen observaciones
