### ISSUE TITLE
Movimiento de reduccion apropiaciones, Mongo + Documentacion y modificacion del modelo 8 horas - Miguel

### ISSUE THREAD

**Issue by miguelramirez93** [udistrital/plan_cuentas_mongo_crud#22]
- [x] crear proceso de reducción en api
- [x] generar documentración de los procesos desarrollados

**Comment by miguelramirez93** [comment]
Se agrega la funcionalidad de registro de movimientos de reducción y su respectiva afectación en (https://github.com/udistrital/plan_cuentas_mongo_crud/commit/757697c2f6687daf1864b24c66fc0f2ef0da81a3)

**Comment by miguelramirez93** [comment]
Se agrega documentación del modelo en MONGO al repositorio correspondiente  (https://github.com/udistrital/Financiera_documentacion/commit/9d881c7928b8c9db15d36becf992df747dc4cea5)

**Comment by miguelramirez93** [comment]
Se realiza PR a repo documentación (https://github.com/udistrital/Financiera_documentacion/pull/5)

**Comment by Soulfilip-UD** [comment]
Quedo pendiente del PR asociado a 'plan_cuentas_mongo_crud' para cerrar el Issue

**Comment by miguelramirez93** [comment]
@Soulfilip-UD listo ya esta el pull request

**Comment by Soulfilip-UD** [comment]
Gracias, Muy buen trabajo!
Proceeding to close Issue 👾
