### ISSUE TITLE
Desarrollo de consulta para obtener información de CDPs Y RPs en Kronos

### ISSUE THREAD

**Issue by a52290451** [udistrital/plan_cuentas_mongo_crud#253]
Se requiere implementar consulta en el API plan_cuentas_mongo_crud que permita obtener información de CDPs y CRPs desde el nuevo sistema de Kronos.

**Criterios de aceptación**

- [x] Commit y despliegue con cambios realizados.
- [x] Pruebas de la consulta.

**Comment by jupmorenor** [comment]
Se realiza carga de la información de prueba obtenida por medio de la consulta en el cliente de Resoluciones satisfactoriamente:
![image](https://user-images.githubusercontent.com/11802554/155594127-832ab7f0-a7d7-443e-9ee3-f8a95ea39af4.png)

**Comment by a52290451** [comment]
Queda pendiente el cambio de fuente de consulta (pasar de SCICapital a Kronos), a falta de salida a producción de Kronos.

**Comment by jupmorenor** [comment]
Relacionado con https://github.com/udistrital/financiera_documentacion/issues/46
