### ISSUE TITLE
Funcionalidades de pre-asignar y asignar apropiaciones en api mongo 

### ISSUE THREAD

**Issue by davidmm07** [udistrital/plan_cuentas_mongo_crud#28]
- [x] Crear Proceso de preasignación inicial en api mongo.
- [x] Crear proceso de asignar apropiacion en api mongo.
- [x] Identificar procesos adicionales requeridos por el cliente.

**Comment by davidmm07** [comment]
endpoint POST 
`/arbol_rubro_apropiacion/Vigencia/UnidadEjecutora`

Ejemplo:
` /arbol_rubro_apropiaciones/2019/1`

Cuerpo de la petición :
```json
{ 
    "_id" : "string", 
    "nodorubro" : {
        "general" : {
            "vigencia" : 2019, 
            "nombre" : "String", 
            "descripcion" : "String"
        }, 
        "hijos" : "[]String", 
        "padre" : "String", 
        "unidadejecutora" : "1"
    },
    "estado": "preasignado",
    "apropiacioninicial" : 1000000,
    "movimientos" : "[]String"
}
```
para este caso esta el estado "preasignado"

**Comment by davidmm07** [comment]
endpoint PUT
`/arbol_rubro_apropiacion/objectid/Vigencia/UnidadEjecutora`
Body: 
```json
{ 
    "_id" : "string", 
    "nodorubro" : {
        "general" : {
            "vigencia" : 2019, 
            "nombre" : "String", 
            "descripcion" : "String"
        }, 
        "hijos" : "[]String", 
        "padre" : "String", 
        "unidadejecutora" : "1"
    },
    "estado": "preasignado",
    "apropiacioninicial" : 2500000,
    "movimientos" : "[]String"
}
```
para este caso esta el estado "preasignado" y asigna la apropiación con un valor de 2500000
endpoint DELETE
`/arbol_rubro_apropiacion/objectId`
solo se envia el _id

**Comment by davidmm07** [comment]
Proceso adicional: para el cambio de estado de aprobación se requiere de un proceso masivo para dejar fijos los valores, requiere de otro issue.

**Comment by Soulfilip-UD** [comment]
Gracias por la documentación, en el daily nos comenta a todos para ver si es viable realizar la tarea de aprobar la apropiación esta semana o la siguiente.

Tarea Realizada
Proceeding to close Issue 👾
