### ISSUE TITLE
Revisar delete y get parar arbol_rubro en api_mongo

### ISSUE THREAD

**Issue by juancsr** [udistrital/plan_cuentas_mongo_crud#3]
Revisar los servicios 
delete
get
del api plan_cuentas_mongo_crud

**Comment by juancsr** [comment]
- [ ] Servicio Delete

- [ ] Servicio Get

**Comment by juancsr** [comment]
Se prueba el servicio delete del api, con la siguiente información:

- **url:** http://localhost:8082/v1/arbol_rubro/eliminarRubro/34
- **parámetros:** ninguno (el parámetro se envía por url)
- **respuesta:** `{ "Type": "success" }`

Antes de eliminar:
https://ibb.co/vdZhc8b

Después de eliminar:
https://ibb.co/sytWPZ4

**Comment by juancsr** [comment]
Se prueba el servicio get del api, con la siguiente información:
- **url:**: http://localhost:8082/v1/arbol_rubro/
- **parámetros:** ninguno
- **respuesta:** https://ibb.co/6mXtcRB

**Comment by miguelramirez93** [comment]
Revisado. No se tienen observaciones
