### ISSUE TITLE
Propagación de saldos en los movimientos (general) - ? Miguel

### ISSUE THREAD

**Issue by miguelramirez93** [udistrital/plan_cuentas_mongo_crud#31]
- [x] desarrollo de algoritmo general de propagación de saldos
- [x] implementación de funciones de propagación en endpoints

**Comment by miguelramirez93** [comment]
en el commit (udistrital/plan_cuentas_mongo_crud@18c2959) se ajusta multiplicador para saldos , de esta forma se puede configurar a nivel parametrico la afectación de cada movimiento sobre su nodo padre

**Comment by Soulfilip-UD** [comment]
Cambios revisados , buen trabajo.
La tarea fue realizada en un :100: 

Proceeding to close Issue :space_invader:
