### ISSUE TITLE
Ajustar registro de hijos en arbol_rubro_apropiacion

### ISSUE THREAD

**Issue by juancsr** [udistrital/plan_cuentas_mongo_crud#33]
Cuando se registra un nuevo nodo con un padre, el arreglo de hijos del padre debe modificarse para que se le agregue el hijo
- [x] Ajustar servicio de registro de arbol_rubro_apropiacion

**Comment by Soulfilip-UD** [comment]
Ahh Camilo , no hubo documentación?
Cambios revisados , tarea finalizada

Proceeding to close Issue :space_invader:

**Comment by juancsr** [comment]
@Soulfilip-UD Documentación del flujo. 

### Este sería un flujo de registro en árbol:

Primero se registra una raíz
![image](https://user-images.githubusercontent.com/19156525/62976352-02475a80-bde2-11e9-9a6d-011b4f6bea94.png)

El registro realizado no tiene ningún hijo asociado.
![image](https://user-images.githubusercontent.com/19156525/62976385-14c19400-bde2-11e9-86cf-5001cbe6364c.png)

Ahora, para registrar un hijo de ese nodo, es necesario hacer otro registro especificando el padre 
![image](https://user-images.githubusercontent.com/19156525/62976425-2d31ae80-bde2-11e9-8f04-b1327973299d.png)

Ahora, se puede apreciar como al registrar un hijo, el atributo Hijos del padre, se actualiza con el hijo recien registrado
![image](https://user-images.githubusercontent.com/19156525/62976482-49cde680-bde2-11e9-9500-8f5a8950200f.png)

**Nota**: Ni la petición POST, ni el endpoint se cambiaron en absoluto en este registro, únicamente la lógica para que corresponda al registro de un nodo aplicación.

**Comment by Soulfilip-UD** [comment]
Gracias por la documentaciòn!
