### ISSUE TITLE
Modelo de Datos Inserción Productos  y relación con Rubros Mongo - 8 horas - Juan Camilo, David

### ISSUE THREAD

**Issue by juancsr** [udistrital/plan_cuentas_mongo_crud#37]
- [x] Proponer el modelo
- [x] Implementar el modelo en el api
- [x] Probar registros con modelo

**Comment by juancsr** [comment]
Se plantea la siguiente estructura para manejar los productos y los rubros:
```json
Producto: {
	"_id": "string",
	"nombre": "string",
	"descripcion": "string"
}
```

Para relacionar los productos con los rubros:
```json
Rubro: {
	"Vigencia": "int",
	"Nombre": "string",
	"Descripcion": "string",
	"_id": "string",
	"Hijos": "[]string",
	"Padre": "string",
	"UnidadEjecutora": "int",
	"ApropiacionInicial": "double",
	"ValorAcumulado": "dobule",
	"FechaCreacion": "date",
	"FechaModificacion": "date",
	"Productos": { "ProductoID": { "ValorDistribuido": "double" } }
}
```

Prestando especial atención al atributo **Productos** la idea es que sea un atributo llave valor (objeto, diccionario, json, etc) cuya llave sea el **_id del producto** (de forma que aseguramos esa llave nunca se repita y el valor de ValorDistribuido sea el correcto para cada producto). Finalmente, si se necesita agregar un nuevo atributo que se de únicamente cuando se relaciona un producto con un rubro, el modelo lo permite, puesto que **ProductoID** puede manejar tantos atributos cómo se necesite (en otras palabras, **agregar más atributos aparte de ValorDistribuido**)

Este modelo se construyo con ayuda de @davidmm07 y se valido con los Ingenieros @Soulfilip-UD  y  @corio27

**Comment by juancsr** [comment]
* **Tipo de petición**: POST
* **Parámetros**:
```json
{
	"Nombre": "Producto dummy 2",
	"Descripcion": "Producto dummy 2",
	"Vigencia": 2019,
	"Activo": true,
	"FechaCreacion": "2018-09-01T05:00:00.000Z",
	"FechaModificacion": "2018-09-01T05:00:00.000Z"
}
```
* **Endpoint**: producto

* **URL**: http://localhost:8082/v1/producto

**Comment by corio27** [comment]
se aprueba modelo

**Comment by Soulfilip-UD** [comment]
Modelo aprobado!, Buen trabajo

Se cierra el Issue , 
Proceeding to close Issue :space_invader:
