### ISSUE TITLE
Pruebas Unitarias a plan_cuentas_mongo_crud - Juan Camilo 

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/plan_cuentas_mongo_crud#40]
Se deben realizar pruebas unitarias a las funciones usadas en Mongo

**Comment by juancsr** [comment]
Avance en pruebas unitarias a:  …
* Managers:
   * rubroManager
  * rubroApropiacionManager
  * movimientosManager

* Helerps:
   * rubroHelper
   * rubroApropiacionHelper

* compositers:
   * movimientoCompositer

@Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Buen trabajo!
Tarea finalizada al 100%

Proceeding to close Issue :space_invader:
