### ISSUE TITLE
Despliegue Mongo 100% se verifica antes del 2/Agosto - JUan Camilo

### ISSUE THREAD

**Issue by juancsr** [udistrital/plan_cuentas_mongo_crud#43]
- [x] Desplegar API

**Comment by juancsr** [comment]
API desplegada en 10.20.0.254:8103/v1/

**Comment by juancsr** [comment]
Se le agrego el atributo **Source**  a la conexión con MongoDB, este atributo especifica la **authenticationDatabase** 
https://github.com/udistrital/plan_cuentas_mongo_crud/commit/72db8801acfc89d810a239b326d42806e7c36eb6

**Comment by Soulfilip-UD** [comment]
Perfecto! :100: 

Proceeding to close Issue :space_invader:
