### ISSUE TITLE
Actualizar la rama cuando se registra o se actualiza una apropiación - Juan Camilo

### ISSUE THREAD

**Issue by juancsr** [udistrital/plan_cuentas_mongo_crud#47]
- [ ] Crear función para actualizar rama
- [ ] Crear endpoint para la función que actualiza el servicio

**Comment by Soulfilip-UD** [comment]
SE devuelve la tarea a la columna BACKLOG y se espera que salga el arbol de rubros al despliegue para continuar con la tarea

**Comment by Soulfilip-UD** [comment]
Issue duplicado

Proceeding to close Issue 👾
