### ISSUE TITLE
Actualizar el padre cuando se registra un hijo en arbol_rubro - Juan Camilo

### ISSUE THREAD

**Issue by juancsr** [udistrital/plan_cuentas_mongo_crud#48]
- [x] Crear transacción para actualizar la rama 
- [x] Ajustar endpoint de POST para que utilice la transacción

**Comment by juancsr** [comment]
La informació del POST no cambia, solamente que ahora se actualiza automáticamente la información del nodo padre.

**Comment by Soulfilip-UD** [comment]
Listo !

Proceeding to close Issue 👾
