### ISSUE TITLE
Registro de apropiación inicial en mongo

### ISSUE THREAD

**Issue by juancsr** [udistrital/plan_cuentas_mongo_crud#5]
- [x] Establecer el parámetro que se debe enviar en el body para la función de registrar apropiación inicial

- [x] Establecer el parámetro que se debe enviar en el body para la función de registrar apropiación inicial cuando se la información de un hijo

- [x] Revisar que el servicio funcione correctamente

**Comment by juancsr** [comment]
- [ ] Establecer el parámetro que se debe enviar en el body para la función de registrar apropiación inicial

- [ ] Revisar que el servicio funcione correctamente

**Comment by juancsr** [comment]
Se prueba el parámetro que se debe enviar en la función:
- **URL:** http://localhost:8082/v1/arbol_rubro_apropiaciones/RegistrarApropiacionInicial/:vigencia
- **Parametros:** 
    - **En url:** _vigencia_
    - **En body:**
```json
{
	"Codigo": "7",
	"UnidadEjecutora": "1",
	"Id": 1,
	"Nombre": "test 3",
	"Descripcion": "pruebaRubromayo302019",
	"ApropiacionInicial": 300
}
```
- **Respuesta:** 
```json
{ "Type": "success" }
```

**Comment by juancsr** [comment]
Registro: https://ibb.co/dJ3PQdQ

Vista Robo3D: https://ibb.co/QkYtDgr

**Comment by juancsr** [comment]
Para registrar el valor de un hijo y que este mismo se propague, es necesario que el padre exista.

Se prueba el parámetro que se debe enviar en la función:
- **URL:** http://localhost:8082/v1/arbol_rubro_apropiaciones/RegistrarApropiacionInicial/:vigencia
- **Parametros:** 
    - **En url:** _vigencia_
    - **En body:**
```json
{
	"Codigo": "7-1",
	"UnidadEjecutora": "1",
	"Id": 34,
	"Nombre": "test 3 hijo",
	"Descripcion": "prueba02junio2019",
	"ApropiacionInicial": 600
}
```
- **Respuesta:** 
```json
{ "Type": "success" }
```

**Descripción adicional**
Siguiendo al rubro registrado anteriormente con el código número 7, cuando se registra el nuevo rubro con código 7-1, hijo del 7, su valor de apropiación inicial se registra y afecta el de su padre. 
(El nuevo valor del padre que antes tenía 300, ahora es 900)

**Cambio visto desde Robo3T:** https://ibb.co/cySzDzC

**Comment by juancsr** [comment]
Se prueba que el servicio de apropiación inicial funciona para cada uno de los nodos del árbol y la información se actualiza correctamente.

**Comment by juancsr** [comment]
merge
https://github.com/udistrital/plan_cuentas_mongo_crud/commit/6881c58faf6532fb6bde1bc5149307e91af1e3e3

**Comment by Soulfilip-UD** [comment]
Bug corregido e Issue finalizado, se cierra el Issue

**Comment by juancsr** [comment]
#4
