### ISSUE TITLE
Completar CRUD fuentes de financiamiento - Juan Camilo

### ISSUE THREAD

**Issue by juancsr** [udistrital/plan_cuentas_mongo_crud#51]
- [x] Función Delete
- [x] Función GetAll
- [x] Función GET

**Comment by Soulfilip-UD** [comment]
Listo , no me regalo la documentación de siempre. Puede agregarse despúes de cerrado el Issue.

Proceeding to close Issue 👾

**Comment by juancsr** [comment]
@Soulfilip-UD Documentación del CRUD completo

### Delete
* **Tipo de petición**: DELETE
* **Parámetros**: Los parámetros se dan en la URL
   * codigoFuente:
* **Endpoint**: fuente_financiamiento/:codigoFuente
* **URL**: http://localhost:8082/v1/fuente_financiamiento/:codigoFuente
![image](https://user-images.githubusercontent.com/19156525/62975977-3cfcc300-bde1-11e9-978c-6fefa8d01229.png)


### GetAll
* **Tipo de petición**: GET
* **Parámetros**: Querys establecido en los controladores de beego (ver https://beego.me/docs/mvc/model/query.md)
* **Endpoint**: fuente_financiamiento/
* **URL**: http://localhost:8082/v1/fuente_financiamiento/
![image](https://user-images.githubusercontent.com/19156525/62975933-22c2e500-bde1-11e9-92aa-c6e8733dad80.png)

### Get
* **Tipo de petición**: GET
* **Parámetros**: Los parámetros se dan en la URL
   * codigoFuente:
* **Endpoint**: fuente_financiamiento/:codigoFuente
* **URL**: http://localhost:8082/v1/fuente_financiamiento/:codigoFuente
![image](https://user-images.githubusercontent.com/19156525/62975965-32422e00-bde1-11e9-8027-b8c67fe23f11.png)

**Comment by Soulfilip-UD** [comment]
Listo!
Gracias por la documentación
