### ISSUE TITLE
Modelo de datos CDP

### ISSUE THREAD

**Issue by juancsr** [udistrital/plan_cuentas_mongo_crud#57]
Generar el modelo de datos para CDPs y CRPs

**Comment by macaguegi** [comment]
Se asocia este issue con la tarea # 14 en el repositorio Financiera Documentación [Issue 14](https://github.com/udistrital/financiera_documentacion/issues/14)

**Comment by macaguegi** [comment]
Se da por terminada esta tarea . Estado 100%. Se solicita revisión de líder técnico @Soulfilip-UD y posteriormente socialización con arquitectos @jairolh , @corio27  y DBA

**Comment by Soulfilip-UD** [comment]
Listo Modelo de datos aprobado y asociado a la socialización del mismo [Link](https://github.com/udistrital/financiera_documentacion/issues/24)

Proceeding to close Issue 👾
