### ISSUE TITLE
Documentación proyecto: plan_cuentas_mongo_crud

### ISSUE THREAD

**Issue by juancsr** [udistrital/plan_cuentas_mongo_crud#6]
Documentar el api plan_cuentas_mongo_crud riñéndose a los estándares de la Oficina Asesora de Sistemas.

- [x] Documentar con el estándar de la OAS
- [x] Actualizar .gitignore

**Comment by juancsr** [comment]
Esta tarea se cumple con los commits:
* Actualizando README.md y .gitignore
https://github.com/udistrital/plan_cuentas_mongo_crud/commit/d69eeac426113cc0efa79cf9b360c369627093d0
* Actualizando docker-compose
Se agrega línea para generar documentación automáticamente al correr los contenedores
https://github.com/udistrital/plan_cuentas_mongo_crud/commit/65234e7446ea5512779d7446be9685be12581418
* Actualizando README.md
Vista previa del api ejecutándose
Especificando para ver documentación en swagger
https://github.com/udistrital/plan_cuentas_mongo_crud/commit/56d7d7c1073f56859c4bd2a3aecd34b1bf4f3931

**Comment by Soulfilip-UD** [comment]
Documentación realizada, Tarea finalizada. Proceeding to close Issue 👾
