### ISSUE TITLE
Corregir registro de arbol_rubro_apropiacion - Juan Camilo

### ISSUE THREAD

**Issue by juancsr** [udistrital/plan_cuentas_mongo_crud#62]
- [x] Corregir el manager del registro
- [x] Documentar la nueva función

**Comment by juancsr** [comment]
En el commit se especifica el error del registro. 
4289bdfa1bdc81ca98036197ed5377018df0767a#diff-5e1efa0f0941e24216fbef166b451457L105

**Comment by juancsr** [comment]
Se revisó el mangager y el post de la petición, el registro funciona correcto. Sólo se agregó la línea ```j.ServeJSON()```para que el servicio vuelva a responder correctamente. 

Petición POST hecha al servidor 10.20.0.254 al api plan_cuentas_mongo_crud
![image](https://user-images.githubusercontent.com/19156525/63136742-09649900-bf99-11e9-98a6-f67bd313afab.png)

_El registro se realiza correctamente_
![image](https://user-images.githubusercontent.com/19156525/63136766-226d4a00-bf99-11e9-8556-0e4dc19a3e7c.png)

**Comment by juancsr** [comment]
La documentación no es neceraría puesto que no se hizo ningún cambio que requiera documentarse. 

El despliegue de esta tarea se hizo en el task 9 de jenkins en plan_cuentas_mongo_crud

**Comment by Soulfilip-UD** [comment]
Entendido, Tarea finalizada. Buena transabilidad de la tarea

Proceeding to close Issue :space_invader:
