### ISSUE TITLE
Corregir registro de productos - Juan Camilo

### ISSUE THREAD

**Issue by juancsr** [udistrital/plan_cuentas_mongo_crud#63]
- [x] Corregir el servicio POST de registro
- [x] Desplegar en el servidor 254

**Comment by juancsr** [comment]
En el commit se especifica el error del registro. 
4289bdf

**Comment by juancsr** [comment]
> En el commit se especifica el error del registro.
> [4289bdf](https://github.com/udistrital/plan_cuentas_mongo_crud/commit/4289bdfa1bdc81ca98036197ed5377018df0767a)

Está en el comentario del cambio en la línea 105 del archivo controllers/producto.go

**Comment by juancsr** [comment]
Registro de un producto en el 254
![image](https://user-images.githubusercontent.com/19156525/63137680-e5a35200-bf9c-11e9-8fdb-daccc54da540.png)

![image](https://user-images.githubusercontent.com/19156525/63137738-01a6f380-bf9d-11e9-9f6f-4c67caed1e3e.png)


El despliegue se hizo en el servidor 254 task 10 del proyecto plan_cuentas_mongo_crud en jenkins

**Comment by Soulfilip-UD** [comment]
perfecto
Buena documentación y especificación
Tarea finalizada

Proceeding to close Issue :space_invader:
