### ISSUE TITLE
Ejecutar refactor en pla_cuentas_mongo_crud - Juan Camilo

### ISSUE THREAD

**Issue by juancsr** [udistrital/plan_cuentas_mongo_crud#64]
- [x] Ejecutar refactor
- [x] Corregir errores si se presentan (opcional)
- [x] Desplegar en 254

**Comment by juancsr** [comment]
El refactor por defecto no puede ejecutarse en el proyecto, debido a que este espera un API basada en la generación por defecto de Beego, y el API plan_cuentas_mongo_crud se genero al partir del generador: https://github.com/udistrital/mda, por tanto su estructura no es la misma de beego.
 
Especificamente los errores se presentan por los comentarios por defecto de las peticiones REST (Get, Post, Put, y Delete) porque algunas de ellas no cuentan con la misma estructura que espera el refactor, otro error también es que los **nombres de métodos propios de cada struct se toman con la letra J**, ejemplo:
### Generador por mda:
```go
func(j *ControllerName) functionName {
 ...
}
```

esto hace que el refactor tampoco pueda reconocer efectivamente dichas funciones **(puesto que espera que se use una C en lugar de una J).**
### Generado por Beego:
```go
func(c *ControllerName) functionName {
 ...
}
```

Puesto que ya se tienen bastantes funciones con el formato de mda, se plantea hacer las correcciones de forma manual, en otras palabras, asegurarse manualmente que cada uno de los servicios del APi devuelva un JSON.

Se propone que el JSON que se devuelva con la siguiente estructura en cada uno de los servicios:
```javascript
{
   Code: "string",
   Message: "string",
   Body: "json"
}
```
Para tener una forma más eficaz y organizada de controlar las respuestas. 

_Pdt: Aún así, para mantener un estándar con otras api que tengan el refactor, los códigos de cada petición se van a mantener como se especifican en los ejemplos de: https://github.com/udistrital/refactor_controller_

**Comment by juancsr** [comment]
Aunque el merge fue correcto, los despliegues # 11 y # 12 en jenkins fallaron, se solicitara colaboración con @Soulfilip-UD para revisar este tema el día martes 20 de agosto. Mientras tanto la tarea sigue abierta.

**Comment by juancsr** [comment]
Despliegue correcto en el servidor 254, se cambio el build de golang_api por golang_api_no_migration. La construcción correcta se hizo en el task # 14

**Comment by Soulfilip-UD** [comment]
perfecto !!! 
gracias por la documentación

Tarea finalizada y revisada
Proceeding to close Issue :space_invader:
