### ISSUE TITLE
Servicio para traer las hojas de rubros y apropiaciones - Juan Camilo

### ISSUE THREAD

**Issue by juancsr** [udistrital/plan_cuentas_mongo_crud#68]
- [x] Funciones para obtener las hojas
- [x] Servicios para las funciones
- [x] Desplegar en 254

**Comment by juancsr** [comment]
### Arbol apropiaciones
* **Tipo de petición**: GET
* **Parámetros**: se envián por URL
   * :unidadEjecutora
   * :vigencia

* **Endpoint**: arbol_rubro_apropiacion/get_hojas/:unidadEjecutora/:vigencia

* **URL**: http://localhost:8082/v1/arbol_rubro_apropiacion/get_hojas/:unidadEjecutora/:vigencia

### Arbol rubros
* **Tipo de petición**: GET

* **Parámetros**: Ninguno

* **Endpoint**: arbol_rubro/get_hojas/

* **URL**: http://localhost:8082/v1/arbol_rubro/get_hojas/

**Comment by juancsr** [comment]
![image](https://user-images.githubusercontent.com/19156525/63433203-5c4eae00-c3e8-11e9-99de-339fe7abbe9f.png)

![image](https://user-images.githubusercontent.com/19156525/63433175-480ab100-c3e8-11e9-9d50-66abd339c4ba.png)

**Comment by juancsr** [comment]
Desplegado en el 254 con el build # 15

**Comment by Soulfilip-UD** [comment]
Gracias Juan Camilo
excelente documentación

Proceeding to close Issue 👾
