### ISSUE TITLE
Servicio para traer las fuentes de financiamiento vinculadas a un rubro - Juan Camilo

### ISSUE THREAD

**Issue by juancsr** [udistrital/plan_cuentas_mongo_crud#70]
- [x] Crear servicio
- [x] Desplegar en 254

**Comment by juancsr** [comment]
* **Tipo de petición**: GET

* **Parámetros**: Se envían por URL
   * :id_rubro_apropiacion

* **Endpoint**: fuente_financiamiento/fuente_financiamiento_apropiacion/:id_rubro_apropiacion

* **URL**: http://localhost:8082/v1/fuente_financiamiento/fuente_financiamiento_apropiacion/:id_rubro_apropiacion

![image](https://user-images.githubusercontent.com/19156525/63470151-75c81800-c431-11e9-93eb-9de65785145c.png)

El servicio devuelve un arreglo de fuentes de financiamiento que tengan en el llaves dentro atributo rubros el id que tengan el mismo valor que el id enviado.

**Comment by juancsr** [comment]
El build se construyo correctamente en el # 17

**Comment by Soulfilip-UD** [comment]
Gracias Juan Camilo
Excelente documentación

Proceeding to close Issue 👾
