### ISSUE TITLE
plan_cuentas_mongo_crud: Aprobación masiva pre-asignación (API) - 16 horas - Camilo

### ISSUE THREAD

**Issue by juancsr** [udistrital/plan_cuentas_mongo_crud#72]
- [x] Crear función
- [x] Crear servicio
- [x] Desplegar en 254

**Comment by juancsr** [comment]
Se desplega en el servidor 254 mediante el build # 19

**Comment by juancsr** [comment]
* **Tipo de petición**: POST
* **Parámetros**: Se envían por URL
   * :unidadEjecutora
   * :vigencia
* **Endpoint**: arbol_rubro_apropiacion/aprobacion_masiva/:unidadEjecutora/:vigencia
* **URL**: http://localhost:8082/v1/arbol_rubro_apropiacion/aprobacion_masiva/:unidadEjecutora/:vigencia

Ej: http://localhost:8082/v1/arbol_rubro_apropiacion/aprobacion_masiva/1/2019

Postman:
![image](https://user-images.githubusercontent.com/19156525/63644346-fe9eb800-c6ac-11e9-8cd8-648cefadba0e.png)

**Comment by juancsr** [comment]
> https://github.com/udistrital/plan_cuentas_mongo_crud/commit/5c544738475d306125ea86b9881589f6a7c13202

Tener presente que como el servicio solo actualiza los estados de las apropiaciones que tengan el estado "registrada", los registros hechos hasta el momento en la BD puede que no tengan un estado asignado. 
En el commit https://github.com/udistrital/plan_cuentas_mongo_crud/commit/5c544738475d306125ea86b9881589f6a7c13202 se establecieron los estados de las apropiaciones y **se modifico el servicio POST de registro para que les asigne automáticamente el estado "registrada***

@davidmm07

**Comment by Soulfilip-UD** [comment]
Entendido, Gracias Juan Camilo
Buena documentación ,

Proceeding to close Issue 👾
