### ISSUE TITLE
Ajuste registro de Apropiaciones para propagar saldo

### ISSUE THREAD

**Issue by miguelramirez93** [udistrital/plan_cuentas_mongo_crud#73]
- [x] Generar función para propagar cambios en saldo apropiaciones al hacer registro

**Comment by miguelramirez93** [comment]
Se ajusta algoritmo para propagar cambios al registrar apropiaciones (https://github.com/udistrital/plan_cuentas_mongo_crud/commit/ea37be9846611e1dba69816c8d9e98f3afaec19d)

**Comment by miguelramirez93** [comment]
Tarea finalizada @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Gracias Miguel , tarea realizada

Proceeding to close Issue 👾
