### ISSUE TITLE
Modelar actividades y metas para Necesidades en MongoDB - 8 horas - Juan Camilo

### ISSUE THREAD

**Issue by juancsr** [udistrital/plan_cuentas_mongo_crud#79]
- [x] Modelo de necesidades
- [x] Funciones CRUD del modelo
- [x] Servicios del modelo
- [x] Documentar modelo

**Comment by CarlosGutierrezArdila** [comment]
Se ajusta el API para guardar el siguiente modelo con sus respectivos métodos CRUD:
```json
{
   "_id" : ObjectId("5d668b4379f72ba4d83902e0"),
   "idAdministrativa" : 102710,
   "rubros" : {
       "codigo" : "3-1",
       "metas" : [
           {
               "codigo" : "meta 1",
               "valor"  : "10000",
               "actividades" : [
                   {
                       "codigo" : "actividad-1",
                       "valor"  : 5000
                   },
                   {
                       "codigo" : "actividad-2",
                       "valor"  : 5000
                   }
               ]
           }
       ]
   },
   "fuentes" : [
       {
           "codigo": "1",
           "valor": 10000
       }
   ],
   "productos": [
       {
           "codigo": "2",
           "valor": 10000
       }
   ],
   "detalleServicio":{
       "codigo" : "1",
       "valor" : 10000,
       "descripcion": "Mantenimiento"
   },
   "tipoContrato" : 0,
   "valor" : 10000
}
```

**Comment by macaguegi** [comment]
Es necesario validar con @juancsr , @Soulfilip-UD y @corio27 respecto al modelo :anguished:

**Comment by juancsr** [comment]
> Se ajusta el API para guardar el siguiente modelo con sus respectivos métodos CRUD:
> 
> ```json
> {
>     "_id": ObjectId("5d668b4379f72ba4d83902e0"),
>     "idAdministrativa": 102710,
>     "apropiaciones": [
>         {
>             "codigo": "3-1",
>             "metas": [
>                 {
>                     "codigo": "meta 1",
>                     "actividades": [
>                         {
>                             "codigo": "actividad-1",
>                             "valor": 5000
>                         },
>                         {
>                             "codigo": "actividad-2",
>                             "valor": 5000
>                         }
>                     ]
>                 }
>             ],
>             "fuentes": [
>                 {
>                     "codigo": "34",
>                     "valor": 10000
>                 }
>             ],
>             "productos": [
>                 {
>                     "_id": "5d668b4379f72ba4d83902e0",
>                     "valor": 10000
>                 }
>             ]
>         }
>     ],
>     "detalleServicio": {
>         "codigo": "1",
>         "valor": 10000,
>         "descripcion": "Mantenimiento"
>     },
>     "tipoContrato": 0,
>     "valor": 10000
> }
> ```

Este modelo se actualizó, el historial de cambios queda en el historial del documento.

**Comment by juancsr** [comment]
Se cancela el checkbox del despliegue puesto que el servidor 254 dejó de funcionar.

**Comment by Soulfilip-UD** [comment]
@macaguegi  y @CarlosGutierrezArdila , entiendo que ya socializaron con @juancsr . 
Pero no entiendo porque se devolvio la tarea a TO DO

**Comment by macaguegi** [comment]
Aún falta realizar documentación del modelo @Soulfilip-UD .

**Comment by macaguegi** [comment]
Se culmina por completo esta tarea . La documentación de este modelo se puede visualizar en el repositorio de Financiera_Documentación :dollar:

**Comment by Soulfilip-UD** [comment]
principalmente es este modelo verdad

> Se ajusta el API para guardar el siguiente modelo con sus respectivos métodos CRUD:
> 
> ```json
> {
>     "_id": ObjectId("5d668b4379f72ba4d83902e0"),
>     "idAdministrativa": 102710,
>     "apropiaciones": [
>         {
>             "codigo": "3-1",
>             "metas": [
>                 {
>                     "codigo": "meta 1",
>                     "actividades": [
>                         {
>                             "codigo": "actividad-1",
>                             "valor": 5000
>                         },
>                         {
>                             "codigo": "actividad-2",
>                             "valor": 5000
>                         }
>                     ]
>                 }
>             ],
>             "fuentes": [
>                 {
>                     "codigo": "34",
>                     "valor": 10000
>                 }
>             ],
>             "productos": [
>                 {
>                     "_id": "5d668b4379f72ba4d83902e0",
>                     "valor": 10000
>                 }
>             ]
>         }
>     ],
>     "detalleServicio": {
>         "codigo": "1",
>         "valor": 10000,
>         "descripcion": "Mantenimiento"
>     },
>     "tipoContrato": 0,
>     "valor": 10000
> }
> ```

Este es el objeto a enviar por postman y este el modelo 
<img width="369" alt="Screen Shot 2019-09-06 at 1 04 39 AM" src="https://user-images.githubusercontent.com/50924615/64404750-86d47400-d042-11e9-9bca-74e7e109a592.png">

Tarea documentada y revisada, lista para cerrar.
