### ISSUE TITLE
Crear servicio para traer árbol de apropiación de acuerdo al estado del árbol

### ISSUE THREAD

**Issue by juancsr** [udistrital/plan_cuentas_mongo_crud#80]
- [x] función para el árbol
- [x] servicio para el árbol

**Comment by juancsr** [comment]
* **Tipo de petición**: GET
* **Parámetros**: Se envían por URL
   * unidadEjecutora
   * vigencia
   * estado
* **Endpoint**: arbol_rubro_apropiacion/arbol_por_estado/:unidadEjecutora/:vigencia/:estado
* **URL**: http://localhost:8082/v1/arbol_rubro_apropiacion/arbol_por_estado/:unidadEjecutora/:vigencia/:estado

Ejemplo: localhost:8082/v1/arbol_rubro_apropiacion/arbol_por_estado/1/2019/aprobada

### Los estados
Los estados que actualmente manejan las apropiaciones son:
* registrada
* aprobada
* rechazada

este es el valor que debe tener el parámetro :estado para que el servicio funcione correctamente.
_Nota: Es indispensable que los registros estén con su estado correctamente asignado para que el árbol se arme bien en cualquiera de los casos_

![image](https://user-images.githubusercontent.com/19156525/63912943-169b7200-c9f4-11e9-97ae-4d84a4997c4b.png)

![image](https://user-images.githubusercontent.com/19156525/63913025-5bbfa400-c9f4-11e9-9195-75a78a9d369d.png)

**Comment by juancsr** [comment]
Debido a que el 254 se encuentra inestable, se remueve el checkbox de despliegue y se pasa a revisión.

**Comment by Soulfilip-UD** [comment]
Listo , buenisima la documentación . 
Retirare la etiqueta de 'bug'  y corregire el título, más esta actividad es más de ustedes

Gracias @juancsr 
Proceeding to close Issue 👾
