### ISSUE TITLE
Incluir SonarQ en plan de cuentas  - ? horas - Juan Camilo, Miguel

### ISSUE THREAD

**Issue by miguelramirez93** [udistrital/plan_cuentas_mongo_crud#88]
- [x] implementar archivo de propiedades sonarqube en API
- [x] Probar funcionamiento de analisis de sonarqube en API
- [x] Desplegar API con analisis en servidor de test

**Comment by Soulfilip-UD** [comment]
tarea retomada, el experto @jjvargass implementa el pipe de SonarQ como requisito para el despliegue en test.

Tarea Finalizada 
Proceeding to close issue 👾
