### ISSUE TITLE
Actualizar modelo de fuentes - Juan Camilo

### ISSUE THREAD

**Issue by juancsr** [udistrital/plan_cuentas_mongo_crud#89]
- [x] Actualizar modelo
- [x] Actualizar documentación del modelo
- [x] Desplegar en rama Test

**Comment by juancsr** [comment]
Actualización del modelo en:
https://github.com/udistrital/financiera_documentacion/commit/315e44775183b6341e230960bf45fdbac138b400

**Comment by Soulfilip-UD** [comment]
tarea revisada, hacia falta agregar los campos de tipo de documento, número de documento en el modelo de datos, este cambio se alcanza a revisar con los arquitectos y dba, asimismo se actualiza la documentación de estos modelos en el repositorio de documentación.

Tarea finalizada
Proceeding to close Issue 👾
