### ISSUE TITLE
**plan_cuentas_mongo** Ajustar respuestas del crud de rubros 

### ISSUE THREAD

**Issue by miguelramirez93** [udistrital/plan_cuentas_mongo_crud#98]
- [x] ajustar respuestas en los procesos de rubros en API

**Comment by miguelramirez93** [comment]
Se termina la tarea. Lista para revisión @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Tarea revisada y desplegada

Proceeding to close Issue 👾
